---
abstract: 'Provide Git status via HTTP'
author:
  - 'Yuuki Tsubouchi <yuuki {at} cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  File::Temp: 0
  File::Which: 0
  Test::More: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.5.6, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-GitStatus
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Plack::Middleware::GitStatus:
    file: lib/Plack/Middleware/GitStatus.pm
    version: 0.02
requires:
  Cache::FileCache: 0
  Git::Repository: 0
  Plack: 0
  Time::Piece: 0
  Try::Tiny: 0
  parent: 0
resources:
  bugtracker: https://github.com/y-uuki/Plack-Middleware-GitStatus/issues
  homepage: https://github.com/y-uuki/Plack-Middleware-GitStatus
  repository: git://github.com/y-uuki/Plack-Middleware-GitStatus.git
version: 0.02
x_contributors:
  - 'y_uuki <yuki.tsubo@gmail.com>'
